### ISSUE TITLE
A question about contextual_loss application in super-resolution

### ISSUE THREAD

**Issue by hahazhky** [roimehrez/contextualLoss#10]
hello, I am trying to re-implement your paper Learning to Maintain Natural Image Statistics, when you adopted srgan, did you train the Discriminator Net to get the results or just Generator Net?
Thanks a lot

**Comment by yanmenglu** [comment]
I'm confused  with that, how to train super resolution using contextual loss. 
@hahazhky  did you have the solution? could you share your training codes.
