### ISSUE TITLE
11144Some run errors?

### ISSUE THREAD

**Issue by zhuangxinfa** [roimehrez/contextualLoss#16]
when I run the code in the ubuntu with python3 tensorflow_gpu1.3 there are some errors in the CSFlow.py line 111and line 44, because the ":" and the "@" in the code  .I do not know why ?but when I run the code using windows there will be no errors?

**Comment by roimehrez** [comment]
we tested it only in Windows so it could be the problem.

**Comment by zhuangxinfa** [comment]
> we tested it only in Windows so it could be the problem.

thank you

**Comment by Jiangzl** [comment]
你好，请问这个实验是不是不可以在ubuntu下使用，或者请问是否找到了可以在ubuntu下使用的方法？

**Comment by sureJ0824** [comment]
你好~同问，有尝试过在Ubuntu里使用吗
