### ISSUE TITLE
Semantic style transfer

### ISSUE THREAD

**Issue by Mona77** [roimehrez/contextualLoss#2]
Thanks for sharing your code. Id like to use contextual losses in [neural style](https://github.com/anishathalye/neural-style) code to reproduce fig 7 of "The Contextual Loss for Image Transformation with Non-Aligned Data" paper.
I'm wondering if you have used the default parameters of the neural style, such as learning rate, weights, #iters [this line](https://github.com/anishathalye/neural-style/blob/master/neural_style.py#L16):

> CONTENT_WEIGHT = 5e0
CONTENT_WEIGHT_BLEND = 1
STYLE_WEIGHT = 5e2
TV_WEIGHT = 1e2
STYLE_LAYER_WEIGHT_EXP = 1
LEARNING_RATE = 1e1
BETA1 = 0.9
BETA2 = 0.999
EPSILON = 1e-08
STYLE_SCALE = 1.0
ITERATIONS = 1000
VGG_PATH = 'imagenet-vgg-verydeep-19.mat'
POOLING = 'max'

**Comment by roimehrez** [comment]
We change many things, see in the paper. I will try to push the code soon.
Regarding the parameters:
LEARNING_RATE = 5e0
ITERATIONS = 300
TV_WEIGHT = 1e-4
STYLE_WEIGHT = 1.0
CONTENT_WEIGHT = 0.5
CX_SIGMA = 0.1
CONTENT_LAYERS = ['relu4_2']
STYLE_LAYERS = ['relu2_1', 'relu3_1', 'relu4_1']#,

and don't forget do concat the style layers features. 

```
def resize_and_concat_features(feat, layers):
    list = []
    sp = feat[layers[0]].shape
    for layer_name in layers:
        feat_resize = tf.image.resize_bilinear(feat[layer_name], (sp[1].value, sp[2].value)) / feat[layer_name].shape[3].value
        list.append(feat_resize)
    stac_feat = tf.concat(list, axis=3)
    return stac_feat
```
