### ISSUE TITLE
sample test issue

### ISSUE THREAD

**Issue by kwkwvenusgod** [roimehrez/contextualLoss#5]
I am trying to use the pretrained model for quick start. But it is producing some results which I don't think are correct. 
![00010_out](https://user-images.githubusercontent.com/9636796/40835388-e8d0108a-65c5-11e8-8f52-5218c78f9f6b.jpg)
As far as I understand, the provided pre trained model is to warp trump animation to some target images. 
So it should be like the one in Fig 1 (left) in https://arxiv.org/pdf/1803.02077.pdf

I really appreciate you that you can give me some hints if there is something wrong I've done.

**Comment by roimehrez** [comment]
It is very hard to know what is the problem, you didn't give any details. 
It might be some version issue? I test it on Windows with tensorflow 1.8 or 1.3. scipy 1.1.0 pyton 3.5 pillow 5.1.
please give more details

**Comment by kwkwvenusgod** [comment]
I tested using MACOS and linux both and both produced result like this.

For the config for Linux:
python 3.5
tensorflow-gpu-1.8
scipy 1.1
pillow 5.1

For MACOS, the configuration is similar except that the tensorflow version is for cpu and python is 3.6.

I will try to use your own dataset in my machine and see.

**Comment by roimehrez** [comment]
did you solve it?

**Comment by kwkwvenusgod** [comment]
I retrain the model using your sample materials. The test result becomes fine using the retrained one. I think that should be the OS issue.

**Comment by zhuangxinfa** [comment]
> I am trying to use the pretrained model for quick start. But it is producing some results which I don't think are correct.
> ![00010_out](https://user-images.githubusercontent.com/9636796/40835388-e8d0108a-65c5-11e8-8f52-5218c78f9f6b.jpg)
> As far as I understand, the provided pre trained model is to warp trump animation to some target images.
> So it should be like the one in Fig 1 (left) in https://arxiv.org/pdf/1803.02077.pdf
> 
> I really appreciate you that you can give me some hints if there is something wrong I've done.

move  the checkpoints in the folder "single_im_CXt32_42_1.0_CXs42_1.0" the problem will be sloved
