### ISSUE TITLE
Comparison with nearest neighbor search

### ISSUE THREAD

**Issue by zhangmozhe** [roimehrez/contextualLoss#7]
Hi, thanks for your code. I am pretty interested in the comparison between the contextual loss and the nearest neighbor search in the feature domain. The contextual loss is defined in a heuristic manner. If I understand correctly, nearest neighbor search is equivalent to minimizing the KL-divergence. Why in the paper the contextual loss always gives less artifact? Is there any intuitive explanation for this?

Thanks a lot!

**Comment by roimehrez** [comment]
What exactly are you asking? I don't think NN as it is minimizing KL. You can look [here ](https://arxiv.org/pdf/1803.04626.pdf) for more analysis of the loss.
