### ISSUE TITLE
Comparison of contextual loss and perceptual loss

### ISSUE THREAD

**Issue by zhangmozhe** [roimehrez/contextualLoss#8]
Hi I really like the paper. One question is that in your super-resolution paper you optimize the contextual loss with conv3_4 features. How about directly minimizing the perceptual loss for the conv3_4 features? What's the visual difference. Thanks!

**Comment by roimehrez** [comment]
What you suggested is exactly what the authors of SRGAN did. The perceptual
quality is a bit less good.

בתאריך יום ו׳, 15 ביוני 2018, 17:09, מאת zhangmozhe ‏<
notifications@github.com>:
