### ISSUE TITLE
some confusions about computing cosine_distance in code

### ISSUE THREAD

**Issue by hahazhky** [roimehrez/contextualLoss#9]
in the paper "The Contextual Loss for Image Transformation with Non-Aligned Data", x_i and y_j need to reduce the mean of the sum of y_j to compute cosine_distance, but i didn't find this operation in either create_using_L2 or create_using_dotP

**Comment by roimehrez** [comment]
`T_features, I_features = cs_flow.center_by_T(T_features, I_features)`
in `create_using_dotP`
